#!/usr/bin/env bash
# install.sh — set up Galley as a macOS background service
# with a menu bar status icon.
#
# What it does:
#   1. Locates the node executable (nvm-aware)
#   2. Builds the React frontend (npm run build) if dist/ is missing
#   3. Creates a start-server.sh wrapper with the correct paths
#   4. Writes a LaunchAgent plist → auto-starts at login, keep-alive
#   5. Compiles main.swift into Galley.app
#   6. Copies the .app to ~/Applications/
#   7. Loads the LaunchAgent (starts the server now)
#   8. Launches the menu bar app
#
# Run once after cloning or moving the repo:
#   bash ops/mac/scripts/install.sh

set -euo pipefail

SERVICE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GALLEY_DIR="$(cd "$SERVICE_DIR/../../.." && pwd)"
SERVER_DIR="$GALLEY_DIR/services/book-server"
WEB_DIR="$GALLEY_DIR/apps/web"
LABEL="com.galley.reader"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LOG="$HOME/Library/Logs/galley.log"
APP_NAME="Galley"
APP_DEST="$HOME/Applications/$APP_NAME.app"

# ── Colours ───────────────────────────────────────────────────────────────────
G='\033[0;32m'; Y='\033[1;33m'; R='\033[0;31m'; N='\033[0m'
ok()   { echo -e "${G}✓${N} $*"; }
warn() { echo -e "${Y}!${N} $*"; }
err()  { echo -e "${R}✗${N} $*" >&2; exit 1; }

echo ""
echo "  Galley — Installer"
echo "  ──────────────────"
echo ""

# ── 1. Find node ──────────────────────────────────────────────────────────────
NODE=""
# Try current shell PATH first
NODE="$(command -v node 2>/dev/null || true)"

# Try nvm
if [[ -z "$NODE" ]]; then
  export NVM_DIR="$HOME/.nvm"
  [[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"
  NODE="$(command -v node 2>/dev/null || true)"
fi

# Try common install locations
if [[ -z "$NODE" ]]; then
  for p in /opt/homebrew/bin/node /usr/local/bin/node /usr/bin/node; do
    [[ -x "$p" ]] && NODE="$p" && break
  done
fi

[[ -z "$NODE" ]] && err "node not found. Install Node.js (https://nodejs.org) and re-run."
ok "node: $NODE ($(${NODE} --version))"

# ── 2. Build React frontend if needed ────────────────────────────────────────
if [[ ! -d "$WEB_DIR/dist" ]]; then
  warn "dist/ not found — running npm run build…"
  cd "$WEB_DIR"
  npm install --silent
  npm run build
  ok "Frontend built"
else
  ok "Frontend already built (dist/ exists)"
fi

# ── 3. Write start-server.sh wrapper ─────────────────────────────────────────
WRAPPER="$SERVICE_DIR/start-server.sh"
cat > "$WRAPPER" <<SCRIPT
#!/bin/bash
# Auto-generated by install.sh — do not edit manually; re-run install.sh.
export NVM_DIR="\$HOME/.nvm"
[[ -s "\$NVM_DIR/nvm.sh" ]] && . "\$NVM_DIR/nvm.sh"
export PATH="/opt/homebrew/bin:/usr/local/bin:\$PATH"
cd "$SERVER_DIR"
"$NODE" run build --prefix "$WEB_DIR" 2>/dev/null || true
exec "$NODE" server.js
SCRIPT
chmod +x "$WRAPPER"
ok "Created wrapper: $WRAPPER"

# ── 4. Write LaunchAgent plist ───────────────────────────────────────────────
mkdir -p "$HOME/Library/LaunchAgents"
cat > "$PLIST" <<XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$WRAPPER</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$LOG</string>
    <key>StandardErrorPath</key>
    <string>$LOG</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>$HOME</string>
    </dict>
</dict>
</plist>
XML
ok "Wrote plist: $PLIST"

# ── 5. Compile Swift menu bar app ────────────────────────────────────────────
echo "  Compiling menu bar app…"
BINARY="$GALLEY_DIR/ops/mac/menubar/Galley"
mkdir -p "$GALLEY_DIR/ops/mac/menubar"
swiftc "$GALLEY_DIR/apps/menubar/src/main.swift" -o "$BINARY" -framework Cocoa \
  2>&1 | sed 's/^/    /'
ok "Compiled binary"

# Build .app bundle
APP_BUILD="$GALLEY_DIR/ops/mac/menubar/Galley.app"
rm -rf "$APP_BUILD"
mkdir -p "$APP_BUILD/Contents/MacOS"
cp "$BINARY" "$APP_BUILD/Contents/MacOS/Galley"

cat > "$APP_BUILD/Contents/Info.plist" <<XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>     <string>Galley</string>
    <key>CFBundleIdentifier</key>     <string>com.galley.reader.menubar</string>
    <key>CFBundleName</key>           <string>Galley</string>
    <key>CFBundleVersion</key>        <string>1.0</string>
    <key>LSUIElement</key>            <true/>
    <key>NSPrincipalClass</key>       <string>NSApplication</string>
    <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
XML
ok "Built .app bundle"

# ── 6. Install to ~/Applications ─────────────────────────────────────────────
mkdir -p "$HOME/Applications"
# Stop running instance before overwriting
pkill -f "Galley" 2>/dev/null || true
sleep 0.3
rm -rf "$APP_DEST"
cp -r "$APP_BUILD" "$APP_DEST"
ok "Installed: $APP_DEST"

# ── 7. Load LaunchAgent ───────────────────────────────────────────────────────
# Unload existing instance if loaded, ignore errors
launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || \
  launchctl unload "$PLIST" 2>/dev/null || true
sleep 0.5

# Load with modern bootstrap; fall back to legacy load
launchctl bootstrap "gui/$(id -u)" "$PLIST" 2>/dev/null || \
  launchctl load "$PLIST"
ok "LaunchAgent loaded — server starting"

# ── 8. Install menu bar LaunchAgent (auto-start at login + relaunch on crash) ─
MENUBAR_LABEL="com.galley.reader.menubar"
MENUBAR_PLIST="$HOME/Library/LaunchAgents/$MENUBAR_LABEL.plist"
MENUBAR_BINARY="$APP_DEST/Contents/MacOS/Galley"

cat > "$MENUBAR_PLIST" <<XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$MENUBAR_LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$MENUBAR_BINARY</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>Crashed</key>
        <true/>
    </dict>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>$HOME</string>
    </dict>
</dict>
</plist>
XML
ok "Wrote menu bar plist: $MENUBAR_PLIST"

# Stop any running instance before (re)loading
pkill -f "Galley" 2>/dev/null || true
sleep 0.3

launchctl bootout "gui/$(id -u)/$MENUBAR_LABEL" 2>/dev/null || \
  launchctl unload "$MENUBAR_PLIST" 2>/dev/null || true
sleep 0.3

launchctl bootstrap "gui/$(id -u)" "$MENUBAR_PLIST" 2>/dev/null || \
  launchctl load "$MENUBAR_PLIST"
ok "Menu bar app launched (auto-restarts at login and after crashes)"

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "  ─────────────────────────────────────────────"
echo -e "  ${G}Done!${N}"
echo "  Reader:     http://localhost:3080"
echo "  Log:        $LOG"
echo "  Server:     $LABEL (auto-starts at login, kept alive)"
echo "  Menu bar:   $MENUBAR_LABEL (auto-starts at login, relaunches on crash)"
echo "  ─────────────────────────────────────────────"
echo ""
