#!/bin/bash
# Auto-generated by install.sh — do not edit manually; re-run install.sh.
export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
cd "/Users/christopherwood/Projects/SunfishSoftware/galley/services/book-server"
"/Users/christopherwood/.nvm/versions/node/v24.15.0/bin/node" run build --prefix "/Users/christopherwood/Projects/SunfishSoftware/galley/apps/web" 2>/dev/null || true
exec "/Users/christopherwood/.nvm/versions/node/v24.15.0/bin/node" server.js
