"""`prose init` — scaffold a book.editorial.yaml for a new or existing book.

Generates a per-book editorial profile populated with sensible defaults
for every registered detector. The yaml that lands becomes the
author-owned configuration the galley/prose pipeline reads via
`BookProfile.from_book_root`.

Contract:
  - Writes `<book_root>/book.editorial.yaml` (the canonical location).
  - Refuses to overwrite an existing file unless `force=True` — the
    yaml is author-owned and may carry hand-tuned values galley should
    never clobber silently.
  - Returns the path written, or raises `FileExistsError` on collision.
  - Output is hand-formatted (not via yaml.dump) so commented sections
    survive — the file is meant to be edited.

Used by:
  - `prose init <book_root>` CLI command.
  - book-server's `/api/books` POST handler (future) to auto-init
    new books registered through the galley UI.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


# ─── Default yaml template ─────────────────────────────────────────────────
# Hand-formatted so commented sections explaining each detector survive
# round-tripping. Per-book values are interpolated with {placeholders}.

_TEMPLATE = """\
# Editorial profile for {book_id}.
#
# Author-owned configuration consumed by the galley/prose pipeline. The
# galley settings UI lays an overlay on top of this file at
# `.galley/editorial.json` (preset scaling + narrator voice); the
# pipeline reads both via `BookProfile.from_book_root`.
#
# Generated by `prose init` on {timestamp}.
# Edit freely. Detectors not listed below use built-in defaults.

book_id: {book_id}
voice: {voice}
genre: {genre}

detectors:

  # ─── Voice detectors ──────────────────────────────────────────────────
  # Anna-decoupling pack. Empty lists = no findings for this book.
  # See galley/prose/lib/prose_telemetry/src/prose_telemetry/detectors/voice/

  filter_words:
    # Narrator-distance verbs of the form "I <verb>". Reducing them
    # moves prose toward sensory immediacy.
    filter_words: []
    # warning_raw_count: 8
    # blocker_raw_count: 20

  motif_overuse:
    # Phrases that should never appear in this book's prose (any
    # occurrence = finding).
    retired_motifs: []
    # Phrases capped per chapter — dict of phrase → max-allowed count.
    motifs: {{}}
    # warning_raw_count: 1
    # blocker_raw_count: 3

  self_referential_frame:
    # Staff-history / meta-frame phrases ("for the record", "in this
    # account", etc.) the narrator should use sparingly.
    self_referential_frames: []
    # warning_raw_count: 2
    # blocker_raw_count: 4

  # ─── Chain detectors ──────────────────────────────────────────────────
  # Generic English stopwords ship as detector defaults. Add book-
  # specific high-frequency register words here so they don't show up
  # as false-positive loops.

  lexical_chain_loop:
    stopwords: []
    # warning_raw_count: 8
    # blocker_raw_count: 20

  bigram_chain_loop:
    extra:
      stopword_bigrams: []     # e.g. [[staff, history], [the, mission]]

  trigram_chain_loop:
    extra:
      stopword_trigrams: []    # e.g. [[the, staff, history]]

  # ─── Compute routing ──────────────────────────────────────────────────
  # Local-first by default. Override per ADR-0007 if the book wants a
  # remote GPU endpoint for heavy detectors.

compute:
  cpu_workers: 4
  gpu_mode: auto
"""


@dataclass
class InitResult:
    """Outcome of an `init` call. `wrote` is True if the file landed,
    False if it was already there and `force=False`."""

    path: Path
    wrote: bool
    skipped_reason: str | None = None


def build_default_yaml(
    book_id: str,
    *,
    voice: str | None = None,
    genre: str = "literary-fiction",
    timestamp: str | None = None,
) -> str:
    """Return the rendered yaml text for a new book profile."""
    if timestamp is None:
        from datetime import datetime, timezone
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return _TEMPLATE.format(
        book_id=book_id,
        voice=voice if voice else "null",
        genre=genre,
        timestamp=timestamp,
    )


def init_book_editorial(
    book_root: Path | str,
    *,
    book_id: str | None = None,
    voice: str | None = None,
    genre: str = "literary-fiction",
    force: bool = False,
) -> InitResult:
    """Scaffold `<book_root>/book.editorial.yaml`.

    - `book_id` defaults to the directory name of `book_root`.
    - Refuses to overwrite existing files unless `force=True`.
    """
    root = Path(book_root).expanduser().resolve()
    if not root.exists() or not root.is_dir():
        raise NotADirectoryError(f"book_root not a directory: {root}")
    target = root / "book.editorial.yaml"
    if target.exists() and not force:
        return InitResult(
            path=target,
            wrote=False,
            skipped_reason="file exists (pass --force to overwrite)",
        )
    resolved_book_id = book_id or root.name
    content = build_default_yaml(
        resolved_book_id,
        voice=voice,
        genre=genre,
    )
    target.write_text(content, encoding="utf-8")
    return InitResult(path=target, wrote=True)
